### ISSUE TITLE
Header file "d3dx12.h" missing, and data definition "CD3DX12_RESOURCE_DESC1" missing.

### ISSUE THREAD

**Issue by lanphon** [microsoft/D3D11On12#2]
Hi All,

Recently I've tried to compile the d3d11on12, but got lots of error. The first one is missing "d3dx12.h", which is included from the "external/d3d11on12.h". By searching on the internet it's found that the "d3dx12.h" is only a helper header file, which could be found inner another project, DirectX-Graphic-samples. I wonder if this header could be placed into the "external/" folder directly, instead of providing such a misleading error information.

What's more, after I copy the "d3dx12.h" and place it under the "external/" folder, the compiler complains that it could not find the definition of "CD3DX12_RESOURCE_DESC1", which is used in line 135 of "external/d3d11on12.h." I've checked the "d3dx12.h" with only CD3DX12_RESOURCE_DESC defined, Is this a typo for the tailing "1"?? Hope it could be confirmed.

Many thanks.

**Comment by lanphon** [comment]
IT's resolved, by using the latest "d3dx12.h"  header file from the D3D12TranslationLayer, not the one used by the DirectX-Graphics-Samples.

**Comment by r2com** [comment]
useless response which does not help
