### ISSUE TITLE
DLL from repository doesn't work with the latest versions of windows.

### ISSUE THREAD

**Issue by IvanPopov** [microsoft/D3D11On12#3]
Hi. I am trying to use this code as an example of usage of D3D12 translation layers. 
I compiled successfully my version of d3d11on12.dll from the code from the repository, but I can not use it instead of the system one.

At the moment, my setup is: Windows 10 64 10.0.18363.836 (latest), Win SDK 10.0.19041.0 (latest or penultimate), WDK same as SDK, VS 2017. 

While running the D3D1211On12 sample from the DirectX-Graphics-Samples (which works fine with system dll) I just put my d3d11on12.dll next to the file and every time I get this error "0x887a0004: The specified device interface or feature level is not supported on this system.". 

I tried to use the d3d11.dll from different versions of Windows, but this did not work. I also tried to debug it, but as far as I can tell the problem inside the d3d11.dll, loading of my version of d3d11on12.dll goes fine and is further unloaded due to mismatches of some flags inside d3d11.dll. 

What else could be wrong, are there any ideas?

Most of the code is understandable, but there are some things that are not obvious, and yet I want to have the ability to debug them.

Many thanks.

**Comment by jenatali** [comment]
I believe that this code currently requires the 19041 OS, which is in insider slow or release preview, to work correctly.

**Comment by jenatali** [comment]
Or I guess, as of today, the latest release OS: https://blogs.windows.com/windowsexperience/2020/05/27/how-to-get-the-windows-10-may-2020-update/

**Comment by IvanPopov** [comment]
> I believe that this code currently requires the 19041 OS, which is in insider slow or release preview, to work correctly.

Thanx for the feedback. I have installed update 10.0.19041.264, but still getting the same error
"0x887a0004 : The specified device interface or feature level is not supported on this system. "
Any other ideas?

**Comment by jenatali** [comment]
Hm, haven't seen that before. I'll take a look and see if I can reproduce it on my side.

**Comment by IvanPopov** [comment]
Sorry, I'm awkward. I forgot to add WinPixEventRuntime.dll also, now everything works, thanks!
The issue can be closed.
