### ISSUE TITLE
GPU shared memory usage grows unbounded using D3D11on12 device with Media Foundation source reader

### ISSUE THREAD

**Issue by bluetarpmedia** [microsoft/D3D11On12#40]
Reproduced on two PCs:

1. Windows 10 21H2 with AMD Radeon RX 5700 XT
2. Windows 11 22H2 with Nvidia GeForce GTX 1660 Ti

When decoding video frames using an `IMFSourceReader` with a D3D11 device created with `D3D11On12CreateDevice` the GPU shared memory usage appears to grow unbounded. If there are enough frames to decode then it will reach the shared memory limit.

With the exact same code using a "real" D3D11 device the GPU shared memory usage remains flat. This is the expected result since each `IMFSample` is decoded and then immediately released.

### Sample code
[D3D11on12.cpp.txt](https://github.com/microsoft/D3D11On12/files/10087923/D3D11on12.cpp.txt)

### Test files
I can repro with any AVC or HEVC video in MP4 or MPEG-TS. But the video stream needs to be long enough before the memory usage can be observed. Decoding 1,000 frames should be enough to at least see a difference between D3D11 and D3D11on12.

Here's a sample file in case you need it. This is the 'main.ts' file referenced in the sample code.
[main.ts](https://bluetarpmedia-my.sharepoint.com/:v:/p/neil/ESYdhCG6Y4VOp6RawoJPvaYBaO_kmse89IxiRyb2EZeXkA?e=Nh3VbT) MPEG-TS with 960x540 AVC (186 MB)

### DxDiag
[DxDiag-AMD.txt](https://github.com/microsoft/D3D11On12/files/10088054/DxDiag-AMD.txt)
[DxDiag-Nvidia.txt](https://github.com/microsoft/D3D11On12/files/10088063/DxDiag-Nvidia.txt)

# Decoding with a "real" D3D11 device:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ![image](https://user-images.githubusercontent.com/2060747/203882043-46e62208-eeec-429d-8366-1286c76a73cf.png)

Video Codec is at 100% and memory usage is flat. This is the expected result.

# Decoding with D3D11on12 device:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ![image](https://user-images.githubusercontent.com/2060747/203882672-ed99c7cb-f55e-424f-ad79-3a6edd278645.png)

The GPU shared memory usage grows linearly as soon as the decoding begins. Interestingly, there is also some Copy work going on that does not appear in the test above.

# Results on Windows 11 with GTX 1660 Ti

The results are similar, though not identical, on a Windows 11 laptop with GTX 1660 Ti.

## D3D11
![image](https://user-images.githubusercontent.com/2060747/203884162-637794c2-6054-4f49-82f6-e26db9bc7fc6.png)

## D3D11on12
![image](https://user-images.githubusercontent.com/2060747/203884194-4a091eca-a453-4a82-a005-abf8dfdaf9a8.png)

**Comment by shawnhar** [comment]
Note: created internal MSFT issue 42398660 to track this.
