### ISSUE TITLE
BUG when using 2D textures

### ISSUE THREAD

**Issue by elad8a** [microsoft/D3D11On12#6]
My app uses the following technologies:

1. wpf (directx 9 UI)
2. directX 11 (simple rendering of textured quads and shapes)
3. opencl (image processing, interoperability with directx 11 via AMD extentions)

hardware: AMD WX7100

The app does not create a swapchain. all rendering is preformed off-screen to a texture.

I replaced the D3D11 device creation code with d3d11on12 code: create a d3d12device and command queue, and call D3D11On12CreateDevice.

Other than that nothing was changed.

The problem I notice is that the textures are rendered incorrectly. It is as if their internal memory layout interpretation has somehow changed. I would guess that this is somehow related to their hardware dependent layout as the way it looks reminds me of the AMD micro-macro texture memory tiling. 

Non-textured geometry seems to be rendered OK.

Here is a simple texture on a quad:

![image](https://user-images.githubusercontent.com/17446835/92304929-3e200580-ef8b-11ea-9796-9d78e474e683.png)

**Comment by jenatali** [comment]
Is there any way for us to reproduce this issue?

**Comment by elad8a** [comment]
@jenatali Currently no.

I did not manage to reproduce this in a simple use case. Our app has many dependencies. but I am working on it.
If someone at Microsoft would like to see this live, I would be glad to help via some form of online session.

I do have a few conclusions though:
- It only occurs on textures shared by Direct3D & OpenCL ([clCreateFromD3D11Texture2DKHR](https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clCreateFromD3D11Texture2DKHR.html)). Standard textures appear alright.
- It appears to happen less if the call to clCreateFromD3D11Texture2DKHR is performed at program start. (not sure about it though).
- The bug also occurs if I force the app to use D3D11On12 via Pix on Windows.

**Comment by elad8a** [comment]
@jenatali I managed to reproduce this bug in a standalone simple application.

It does the following:
1. Create d3d11in12 device and context.
2. Obtain opencl device and context from d3d11device (clGetDeviceIDsFromD3D11KHR).
3. Create 2 distinct d3d11 textures.
4. Use opencl (clCreateFromD3D11Texture2DKHR) to obtain an 2 opencl image objects (cl_mem).
5. Write the same content to each opencl image via a very simple opencl kernel.
6. copy back / present the directx textures.

Results:
- First created texture is fine. If I present it or download it to the RAM. it looks as expected.
- Second texture looks bad - like the picture I uploaded.
- If I download the second texture (image) via the opencl API, it looks fine. it is as if the directx driver somehow misinterpret its memory layout.

the code has the following dependencies:
- AMD GPU
- boost libraries. opencv (for easy debugging via image watch)
- I can create an .exe without opencv and boost, whatever suits you. let me know.

How can I transfer you the files?

**Comment by elad8a** [comment]
@jenatali A link with a self contained VS2019 solution that reproduce this bug:

[link](https://1drv.ms/u/s!ApkpQgJnXKOBgpo9K24NjJGo5PJx8Q?e=Bfejls)

Let me know if there's any problem.
I appreciate you help!

Elad.

**Comment by jenatali** [comment]
Cool, thanks for the solution. I can reproduce the issue. I suspect I won't be able to solve it, and we'll probably need AMD to take a look, but at least I can try to see what's going on.

**Comment by elad8a** [comment]
@jenatali any update on this issue? I reported this to AMD as well: [link ](https://community.amd.com/thread/256535). But from experience I doubt they will do something about it.

D3D11On12 is our only chance of being able to integrate DirectX12 & DirectML workloads into our project. 

I appreciate your help very much.
Elad

**Comment by jenatali** [comment]
@elad8a I also reached out to AMD's OpenCL team. This appears to be a communication issue between their OpenCL driver and D3D12 driver.

**Comment by jenatali** [comment]
I haven't heard any updates from AMD on this issue, but this doesn't appear to be something that will be fixed in D3D11On12 itself, so I'm going to close this issue here.
